sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- "8"
cache:
  directories:
  - node_modules
before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
deploy:
- provider: npm
  email: admin@swyftx.com.au
  api_key: $NPM_TOKEN
  tag: beta
  on:
    branch: dev
    node: "8"
- provider: script
  script: "node tagAsLatest.ci.js"
  on:
    branch: master
    node: "8"
