language: node_js
node_js:
- '8.12'
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms: $SLACK_TOKEN
before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
deploy:
- provider: npm
  email: admin@swyftx.com.au
  api_key: "$NPM_TOKEN"
  tag: beta
  on:
    branch: dev
- provider: script
  script: node ci/tagAsLatest.ci.js
  on:
    branch: master
